# Generated by Django 5.0.4 on 2024-04-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_created_at_cart_updated_at_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',)},
        ),
    ]
