# Generated by Django 5.0.4 on 2024-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('P', 'PENDING'), ('C', 'CASH'), ('K', 'KHALTI')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[('P', 'PENDING'), ('CF', 'CONFIRM'), ('R', 'REJECTED'), ('C', 'CANCELLED')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
