# Generated by Django 5.0.4 on 2024-04-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='middle name'),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
